# Generated by Django 2.2.1 on 2019-05-16 18:15

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shortenedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=3000000, validators=[shortener.validators.valid_url])),
                ('short', models.CharField(blank=True, max_length=100000000, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
