# Generated by Django 2.2.1 on 2019-05-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shortenedUrl',
            new_name='Url',
        ),
    ]
