# Generated by Django 2.2.1 on 2019-05-16 18:42

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20190517_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(blank=True, max_length=3000000, null=True, validators=[shortener.validators.valid_url]),
        ),
    ]
